### ISSUE TITLE
There is the exception when run the example.

### ISSUE THREAD

**Issue by thanhvc** [zandero/rest.vertx.example#1]
I'm using JDK 1.8-216 to compile, Everything is OK. However when run following the command:
java -jar target/rest.vertx.example.jar -p 5555
The exception occurs as bellow: Please help me if I'm wrong.
 
SEVERE: io.vertx.core.http.HttpMethod.values()Ljava/util/List;
java.lang.NoSuchMethodError: io.vertx.core.http.HttpMethod.values()Ljava/util/List;
	at com.zandero.rest.data.RouteDefinition.method(RouteDefinition.java:642)
	at com.zandero.rest.data.RouteDefinition.init(RouteDefinition.java:417)
	at com.zandero.rest.data.RouteDefinition.<init>(RouteDefinition.java:192)
	at com.zandero.rest.AnnotationProcessor.getDefinitions(AnnotationProcessor.java:247)
	at com.zandero.rest.AnnotationProcessor.collect(AnnotationProcessor.java:96)
	at com.zandero.rest.AnnotationProcessor.get(AnnotationProcessor.java:39)
	at com.zandero.rest.RestRouter.register(RestRouter.java:112)
	at com.zandero.rest.RestRouter.register(RestRouter.java:71)
	at com.zandero.rest.RestBuilder.getRouter(RestBuilder.java:495)
	at com.zandero.rest.RestBuilder.build(RestBuilder.java:568)
	at com.zandero.rest.example.ServerVerticle.start(ServerVerticle.java:79)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

**Comment by thanhvc** [comment]
That's the issue on my environment. It's working well now.

**Comment by drejc** [comment]
No problem ... haven't had the time to look into it anyway. 
PS: The example project is not maintained / on the last state of things ... so check out original project unit tests to get a clearer picture.
